project_id = "oasrfhocuaqazvfmrtid"

[functions.extract-pdf-data]
verify_jwt = false

[functions.extract-revestimento-medidas]
verify_jwt = false

[functions.extract-openings-doors-gates]
verify_jwt = false

[functions.extract-floor-measurements]
verify_jwt = false
