name: Automatic Backup

on:
  push:
    branches:
      - main
      - dev

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create backup folder
        run: |
          mkdir backup
          cp -r * backup/ || true

      - name: Commit backup snapshot
        run: |
          git config --global user.name "backup-bot"
          git config --global user.email "backup@bot.com"
          git add .
          git commit -m "Automatic backup snapshot" || echo "No changes"

      - name: Push backup
        run: git push
